AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  purpleairgateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: purple_air_gateway
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: purple_air/
      Description: ''
      MemorySize: 128
      Timeout: 7
      Role: 'arn:aws:iam::564844288026:role/service-role/iqair-gateway-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /purpleair
            Method: GET
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: /opt/nodejs/aqi-gateway-d19ea6ab0844.json
          PURPLE_AIR_KEY: CDB7F040-F990-11EA-910A-42010A800178
      Layers:
        - 'arn:aws:lambda:us-east-1:564844288026:layer:axios:1'
        - 'arn:aws:lambda:us-east-1:564844288026:layer:google-credentials:1'
        - 'arn:aws:lambda:us-east-1:564844288026:layer:google-datastore:1'
        - 'arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:14'
