version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "purpleAir-app"
s3_bucket = "aqi-lambda-fns"
s3_prefix = "purpleAir-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
