name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name aqi-gateway-sam -t aqi_gateway/purple_air_gateway.yaml --s3-bucket aqi-lambda-fns --capabilities CAPABILITY_IAM --region us-east-1
